import type { NextPage } from 'next'
import Head from 'next/head'
import { useCallback, useState } from 'react'
import { signIn } from 'next-auth/react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'

import { loginSchema, ILogin } from '../../common/validation/auth'
import Sidebar from '../../components/shared/Sidebar'
import SignInForm from '../../components/sign-in/Form'
import HorizontalCard from '../../components/shared/UI/Cards/Horizontal'

const Home: NextPage = () => {
  const [isLoading, setIsLoading] = useState<boolean>(false)
  const { register, handleSubmit } = useForm<ILogin>({
    resolver: zodResolver(loginSchema),
  })

  const onSubmit = useCallback(async (data: ILogin) => {
    setIsLoading(true)
    await signIn('credentials', { ...data, callbackUrl: '/store' })
  }, [])

  return (
    <div>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="w-full flex flex-row justify-between">
          <SignInForm
            isLoading={isLoading}
            register={register}
            onSubmit={handleSubmit(onSubmit)}
          />
          <Sidebar>
            <Sidebar.TitleContainer>
              <Sidebar.Title>
                Join the biggest <br /> e-cleaning platform.
              </Sidebar.Title>
              <Sidebar.SubTitle>
                Discover the very best cleaning products for your bussiness or
                household. All accross the country.
              </Sidebar.SubTitle>
            </Sidebar.TitleContainer>
            <Sidebar.FooterContainer>
              <HorizontalCard />
            </Sidebar.FooterContainer>
          </Sidebar>
        </div>
      </main>
    </div>
  )
}

export default Home
