import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="hero min-h-screen bg-base-200">
        <div className="hero-content text-center">
          <div className="max-w-md">
            <h1 className="text-5xl font-bold">Limpieza Libre</h1>
            <p className="py-6">
              Bienvenido a la mejor tienda de productos de limpieza en la
              actualidad
            </p>
            <button className="btn btn-primary">Comenzar</button>
          </div>
        </div>
      </div>
    </div>
  )
}
